### ISSUE TITLE
Weapons list not working

### ISSUE THREAD

**Issue by Robofries** [fabianwennink/Call-of-Duty-Gun-Game#1]
I created a weapons list, and I'm pretty sure I have it set up right. (I can't find the settings file, so I downloaded it from here), and it's not working.  How can I fix this?

**Comment by fabianwennink** [comment]
A custom weapons list only works on a dedicated server _(so not on a local server which you can start from the game itself)_. If you have use a dedicated server, you need to [decompile the addon](https://steamcommunity.com/sharedfiles/filedetails/?l=dutch&id=431638110) and put the decompiled folder in the /gamemodes/ folder in your server. In the folder itself you will find the settings file.
